### ISSUE TITLE
Missing alignment of buf array in handlebyte() function

### ISSUE THREAD

**Issue by martinayotte** [Edzelf/Esp-radio#1]
The buffer declaration need alignment attribute : 

https://github.com/Edzelf/Esp-radio/blob/master/Esp_radio.ino#L1270

It should be changed as follow : 

`static __attribute__((aligned(4))) uint8_t  buf[32] ;                            // Buffer for chunk`

**Comment by Edzelf** [comment]
Yes, you are right.  Did not get any exceptions here, but I guess that it is a
change of 25 percent.
I wil update the code tomorrow.

Thanks for your feedback,
Ed.
--------------------------------------------------------------------------------


Op 24-04-16 om 23:30 schreef martinayotte:

**Comment by martinayotte** [comment]
Of course !
The fact that I've commented out the TFT probably make the bug coming up, I had 75% bad luck on my side ... :-)

**Comment by Edzelf** [comment]
No need to comment out the TFT.  Software will work without it.  In fact it will
even work without the VS1053...


Op 25-04-16 om 03:36 schreef martinayotte:
