### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by bnq2** [Edzelf/Esp-radio#108]
Hi everyone, i have a problem with compilation this script. I installed all librarys and i put all files in my project folder. The compiler sees the all html.h files, but during installation, the IDE tries to compile HTML (so I think).  How can I fix it? Please help, I really want to finish this great project ;] 

These are my logs  [http://wklej.org/id/3268443/](url)

**Comment by Edzelf** [comment]
The link does not work.

**Comment by bnq2** [comment]
sorry, its problem with this serwise, it works when you put it in browser

**Comment by Edzelf** [comment]
Can you list the first 10 lines of the file about_html.h please?

**Comment by bnq2** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">








<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">

**Comment by bnq2** [comment]
The file starts with 8 new lines, and then :
http://wklej.org/id/3268502/

**Comment by skakri** [comment]
Did you copy about_html.h or did you clone this repo? Error is related to invalid characters – https://stackoverflow.com/questions/19198332/compilation-error-stray-302-in-program-etc

**Comment by Edzelf** [comment]
The file about_html.h is only 38 lines long.  You are using the wrong method to download the sourse files.

**Comment by bnq2** [comment]
Bingo! I copied the text from a file in a repo to a notepad and saved it to *.h in ANSI ;] now compilation is correctly ;] tommorow i try upload it to ESP. Realy THX ;]
