### ISSUE TITLE
Posion of display text

### ISSUE THREAD

**Issue by amigafan** [Edzelf/Esp-radio#119]
I have a 128 x 160 pixel display connected and it works fine. But sometimes the metadata text overlaps the station's name. Is it possible to move the station name down, there is plenty of space?

**Comment by Edzelf** [comment]
Yes, it is easy to change the position.

**Comment by amigafan** [comment]
How?

**Comment by jgrulich** [comment]
Already solved in my version. There different TFT Lib and therefor better text font and changed completely the text layout.
Look here: https://github.com/jgrulich/Esp-radio.

**Comment by amigafan** [comment]
I I really like your layout, but for some reason I can not connect to any stations! It keeps trying but it does not succeed.

**Comment by jgrulich** [comment]
This happened to me too with the ESP8266 core 2.4.0. Working is only 2.3.0.
Or reflash the radio.ini once again, sometimes it needs hard reset, or reflash program ...
Really don't know what happens there in this "Black box" called ESP.
I've also found very useful disabling of ArduinoOTA, which makes it much more stable and web response faster. Try this version: https://github.com/jgrulich/Esp-radio/tree/OTA-Disabled.

**Comment by amigafan** [comment]
Thank you, I changed to version 2.3.0 and now everything works perfectly
