### ISSUE TITLE
SD card reader on VS1053

### ISSUE THREAD

**Issue by h1aji** [Edzelf/Esp-radio#149]
Some of the VS1053 modules comes with embedded SD card reader. IS there any way to read mp3 files from it?

**Comment by Edzelf** [comment]
The ESP32 version supports SD cards.

**Comment by h1aji** [comment]
Do you plan to add this feature for Esp8266? Would be nice to have it

**Comment by Edzelf** [comment]
No, I like to add new features to the ESP32 version only.
