### ISSUE TITLE
Adafruit Huzzah?

### ISSUE THREAD

**Issue by bickyb** [Edzelf/Esp-radio#15]
Hi,
I saw that the ESP-12 was used for this project.  I wanted to see if you think the following can be used instead:
https://learn.adafruit.com/adafruit-feather-huzzah-esp8266/overview

**Comment by Edzelf** [comment]
According to the datasheet the Huzzaz should be able to run the Esp-radio.  There are also some cheap Chinese NodeMCU clones that can be used.
