### ISSUE TITLE
Wemos D1 R1 +JUMPER MOD GEEETECH VS1053B + SOLAR POWERED = 24/7 WEBRADIO (Amp powerup not included)

### ISSUE THREAD

**Issue by SurenBono** [Edzelf/Esp-radio#151]
...recently i managed a OTA sketch upload for some variety of blinking leds on a Wemos D1 R1... but later i wanted more...so i encountered a uno plugable VS1053 & UNO plugable Touch display....but i cant find a similar sketch for it... i tried all the sketches near similar that i can find online  but nothing worked...i can upload the sketches but i can only hear a pulsing sound on my amp....can anybody make a custom sketch for such combination..?...please help
![20181128_210450](https://user-images.githubusercontent.com/45394551/49154806-5eea0e80-f354-11e8-8eda-47f292e4475d.jpg)
![20181128_210527](https://user-images.githubusercontent.com/45394551/49154817-66a9b300-f354-11e8-942b-972db0226fbe.jpg)
![screenshot 2](https://user-images.githubusercontent.com/45394551/49154877-8b058f80-f354-11e8-9804-88156feb353c.jpg)
![screenshot 1](https://user-images.githubusercontent.com/45394551/49154903-9789e800-f354-11e8-8e54-5478a6b60e8e.jpg)

**Comment by SurenBono** [comment]
...after hundreds of error i only managed to list out my WEBRADIO on the wifi...hehe..but still no sound yet coming out of it...complex codes that i not understand..just copy from others with somewhat similar hardware but different pin config..i think it will be my lifes project to get it working like the other guys..this will be my advance studies in multimedias....

**Comment by Edzelf** [comment]
Just publish your debug output.  The answer lies in there.

**Comment by SurenBono** [comment]
At first try i had some issues to resolve like additional libraries to install through the debug output
.... the debug output points to nodemcu while my board are of wemos d1...i tried copying the D1/ pins_arduino.h into node mcu folder after backing up the nodemcu/ pins_arduino.h...i could upload the sketch successfully but just blipping sound...do i need the tft to run it..?..or is the radio.ini in the right folder..?
![nodemcu vs d1r1](https://user-images.githubusercontent.com/45394551/49204995-8c809780-f3e8-11e8-946a-32706fca1952.JPG)

**Comment by SurenBono** [comment]
![screenshot 2](https://user-images.githubusercontent.com/45394551/49205106-eed99800-f3e8-11e8-8ede-662120ff0764.jpg)

**Comment by SurenBono** [comment]
![debug output](https://user-images.githubusercontent.com/45394551/49208221-23058680-f3f2-11e8-8861-0dab29bad616.GIF)

**Comment by Edzelf** [comment]
That's not the debug output.  I mean the output to the Serial when you start the radio.  You may compare it with the example debuf output in the last page of the documentation.    It should start like this:
```
D: FS Total 2949250, used 2145297
D: /radio.ini                       -    1780
D: /friendly.mp3                    -  281941
D: /kontiki.mp3                     - 1843200
D: Added SSID 00 = NETGEAR-11 to acceptable networks
D: Added SSID 01 = ADSL-11 to acceptable networks
D: * Scan Networks *
D: Number of available networks: 8
D:  1 - HZN240825082              Signal: -73 dBm Encryption WPA2  
D:  2 - Private_FON               Signal: -56 dBm Encryption WPA   
D:  3 - FON_Roulet_11             Signal: -56 dBm Encryption None  
D:  4 - ADSL-11                   Signal: -86 dBm Encryption Auto  Acceptable
D:  5 - Roulet 9 Gast             Signal: -88 dBm Encryption Auto  
D:  6 - Roulet 9                  Signal: -87 dBm Encryption Auto  
D:  7 - NETGEAR-11                Signal: -58 dBm Encryption WPA2  Acceptable
D:  8 - TWEED                     Signal: -86 dBm Encryption WPA2  
D: --------------------------------------
D: Command: wifi_00 with parameter NETGEAR-11/XXXXXXXX
D: Command: wifi_01 with parameter ADSL-11/YYYYYYY
D: Command: volume with parameter 72
D: Command: toneha with parameter 0
D: Command: tonehf with parameter 0

```

**Comment by SurenBono** [comment]
![20181129_162542](https://user-images.githubusercontent.com/45394551/49209487-952b9a80-f3f5-11e8-96f2-ac593a885937.jpg)

**Comment by SurenBono** [comment]
...ohh....ok..
![screenshot 1](https://user-images.githubusercontent.com/45394551/49209918-c6589a80-f3f6-11e8-884a-d58b7ddd9725.jpg)

**Comment by SurenBono** [comment]
how do i upload the radio.ini file...?

**Comment by SurenBono** [comment]
Trying to connect to the  AP #define NAME //line202 adding a #define PASSWORD .. //line203
WiFi.softAP (  NAME, PASSWORD ) ; //line1407..... the ap shows up a bit later..so i can login and upload the radio.ini through the browser...but it cant register a ip yet

**Comment by Edzelf** [comment]
To upload the .ini file: use the "ESP8266 sketch Data Upload" in the IDE.  See page 2 of the document.....

**Comment by Edzelf** [comment]
Connect to AP: see page 12 of the document.

**Comment by SurenBono** [comment]
finally got the radio.ini file uploaded through a smart phone ....the laptop wifi was skipping connecting to the esp since it was a slow connection...happy that i archieved something today..thanks bro...but got lot more to figure out
![radio ini-upload-sucess](https://user-images.githubusercontent.com/45394551/49226263-14829380-f421-11e8-99dd-3020732d0e6d.GIF)

**Comment by SurenBono** [comment]
> Just publish your debug output. The answer lies in there.

**Comment by SurenBono** [comment]
> Just publish your debug output. The answer lies in there.

**Comment by SurenBono** [comment]
..thats the serial monitor

**Comment by SurenBono** [comment]
![vs1053b pin](https://user-images.githubusercontent.com/45394551/49280021-fde14880-f4c3-11e8-833c-5e5c2fc956a5.JPG)

**Comment by SurenBono** [comment]
Finally i got it sounding like its suppossed to bro.... i fritz the VS1053B since the x_DCS & X-CS pin is in conflict with the MOSI & MISO on D1....but i got to work on the buffer later for smoother play...its sounds skanky...but better than nothing within my budget....i want to let you know so that you could comment on other guys who is trying the same module
![sucided pin](https://user-images.githubusercontent.com/45394551/49340721-eef2c580-f67e-11e8-8230-71a181d8a520.jpg)
![20181202_213719](https://user-images.githubusercontent.com/45394551/49340728-f87c2d80-f67e-11e8-9ee7-99f435f63522.jpg)

**Comment by SurenBono** [comment]
check my skanky webradio on WeMos D1 R1 + VS1053--->  https://youtu.be/o-9Ow0_Cs9o

**Comment by SurenBono** [comment]
https://youtu.be/jKUjhhCNEgg

..now i got to figure out how to add a 1602 LCD BUTTON SELECTION from the esp32webradio sketch... can u guide me..?

**Comment by SurenBono** [comment]
..Working on a ESP32 WeMos D1 R32  but error uploading the blink sketch after installing the Expressif ESP32 platform...while listening to my perfected ESP8266 EDZELF WEBRADIO..not sure if its compatible with xp or is a 64bit board...considering a ESP32 LYRA board where comes with a stereo out ..but cant find sites that sell one..

![20181206_000419](https://user-images.githubusercontent.com/45394551/49564236-d116b080-f95d-11e8-8d67-b6fe27a4f1a2.jpg)
![for-esp32-wifi-bluetooth-4mb-flash-for-wemos-d1-r32-development-board-module-for-arduino-uno](https://user-images.githubusercontent.com/45394551/49564295-fb686e00-f95d-11e8-8806-e5640d674b46.jpg)
![esp32-lyrat](https://user-images.githubusercontent.com/45394551/49564373-44202700-f95e-11e8-8ccc-d8ee3b6596e8.jpg)

**Comment by SurenBono** [comment]
![47140211_10218009317923357_2679500834638659584_n](https://user-images.githubusercontent.com/45394551/49566463-a7fa1e00-f965-11e8-9771-081f08037b04.jpg)

**Comment by SurenBono** [comment]
![possible flowchart](https://user-images.githubusercontent.com/45394551/49570718-602dc380-f972-11e8-826d-1ab1dac68825.GIF)


...I think this is whats goin on there...

**Comment by SurenBono** [comment]
...trying to create a new variant for WeMos Wroom esp32 R32  ...seem not working on xp...i need a 64-bit OS for this most probably....
![r32 pinout](https://user-images.githubusercontent.com/45394551/49657029-a6ba1580-fa79-11e8-829d-71870c93011e.GIF)
![screenshot 5](https://user-images.githubusercontent.com/45394551/49657048-b76a8b80-fa79-11e8-9775-a822a1a7283f.jpg)

**Comment by SurenBono** [comment]
...working on a 4-bit 1602 BUTTON LCD to add into the sketch...the pinout is RS=9(D1.8266=0) ,EN=8(D1.8266=2) ,DB4=4(D1.8266=4) ,DB5=5(D1.8266=14),DB6=6(D1.8266=12),DB7=7(D1.8266=13).5-BUTTON=A0...only worked on hd44780....
![dsc00452](https://user-images.githubusercontent.com/45394551/49801601-9493ec00-fd85-11e8-9fa0-dba743108f52.JPG)
![dsc00454](https://user-images.githubusercontent.com/45394551/49801608-9bbafa00-fd85-11e8-92f9-928c84d0a7e9.JPG)
![dsc00455](https://user-images.githubusercontent.com/45394551/49801613-9eb5ea80-fd85-11e8-8f70-ad039301b8f4.JPG)

**Comment by SurenBono** [comment]
![collected arduino pinout reference](https://user-images.githubusercontent.com/45394551/49801708-dd4ba500-fd85-11e8-995d-33ca16041866.GIF)

**Comment by SurenBono** [comment]
![d1 esp8266-webradio-interface-suggestion](https://user-images.githubusercontent.com/45394551/49959841-ac1bd200-ff49-11e8-87f2-561eade6a054.GIF)
![alt 8266 webradio interface wiring](https://user-images.githubusercontent.com/45394551/49959870-bccc4800-ff49-11e8-9911-b51ea870deff.GIF)

**Comment by SurenBono** [comment]
![edzelf esp8266 webradio alternate module srotogargees version](https://user-images.githubusercontent.com/45394551/49968769-c497e680-ff61-11e8-8fb7-cc698032c73a.GIF)

**Comment by hihiman1** [comment]
Hi SurenBono,
could you please describe in detail how you modified the sktech to enable the lcd keypad shield?
- which part of the sketch (used for TFT display) is changed into comment
- where do have add the values for A0 to use the four buttons

Could you upload a picture of the jumper from LCD's pin D7 & D6 to the Wemos D1?
Is it possible to realize this modification without soldering?

Thanks in advance
HiHiMan

**Comment by SurenBono** [comment]
Hi,
1.the LCD which was not i2s did not work on d1r1.
2.I could work those LCD  buttons if the A0 were as same as uno board but
would not be a proper addon since the LCD was not compatible for d1r1.
3.Do not uncommented the TFT even for bare minimum setup it just was not
smooter without.
4.you could try a D1r2 board or recommend a r3 version with RX & TX to D6 &
D7

**Comment by hihiman1** [comment]
Hi,
bought a wemos D1 R32 - works perfectly with the VS1053 shield!
Next I will check if the LCD shield will also work...

**Comment by SurenBono** [comment]
..esp32 R32 did not...on me ..it sounded like a blaring ..lacking of
something...but it was perfect on esp8266 with only when TFT were
uncommented... and it's not 5g thingy ,and only little more speedy than
simple esp8266...if you tested the LCD with a non i2c it probably a rare
one..let me know if it worked, include the test on a A0 buttoned LCD
