### ISSUE TITLE
Where to hookup audio amplifier

### ISSUE THREAD

**Issue by bickyb** [Edzelf/Esp-radio#18]
Hi,
One thing I could not figure out from the circuit diagrams is how you are connecting the audio amplifier to the VS1053 board.
The VS1053 board has a 3.5mm output which can be connected to headphones.
What is a bit unclear to me is how you can connect the audio amp to the VS1053 board.  Do you have a cable plugged into the 3.5 jack and are you tapping into the audio from the line level out or do you somehow connect the amplifier to the VS1053 board directly?

Also, can you please let us know an example of the type of amplifier you used in your circuit?

**Comment by Edzelf** [comment]
The audio amplifier is connected through the 3.5 mm output jack.  Note that the common pin of the output jack is not at ground level.  Therefore I used a separate power circuit (battery) for the amplifier.

For the amplifier I used a cheap class D type base on a PAM8403 chip ( 2 dollar for 10 pieces).
