### ISSUE TITLE
How to Support rtmp

### ISSUE THREAD

**Issue by pasagame** [Edzelf/Esp-radio#20]
Hi
I found this link. How to use.
rtmp://203.145.115.34/Eazy/Eazy-Listen-High

file=efm.sdp&amp;volume=100&amp;streamer=rtmp://real3.atimemedia.com/live&amp;autostart=true&amp;repeat=always&amp;stretching=exactfit

thank you.

**Comment by Edzelf** [comment]
No idea, it does not seem a standard mp3 stream.

**Comment by pasagame** [comment]
Thank You.
