### ISSUE TITLE
Migrate to Platformio

### ISSUE THREAD

**Issue by h1aji** [Edzelf/Esp-radio#202]
Hi @Edzelf are you planning to migrate this code platformio? Same you did for esp32-radio?
Thanks

**Comment by Edzelf** [comment]
No, but it should not be too difficult to do this.  I guess it is just a matter of renaming the sketch and add a line to include "arduino.h".

**Comment by h1aji** [comment]
Thanks for your reply. Just created for with Platformio here - https://github.com/h1aji/Esp-radio.
Replaced digital buttons control with Infra-red
I want to replace ILI9361 with LCD 2004 now, any help welcome
