### ISSUE TITLE
Setting up the 128x160 display

### ISSUE THREAD

**Issue by samand587** [Edzelf/Esp-radio#210]
Dear author! This is the image the display displays. The display applied the recommended one in the project.
How can this be fixed? Thanks!   
![IMG_20211104_132813](https://user-images.githubusercontent.com/82581244/140284394-83e0326a-3563-42ac-a8af-bd3b8e29566a.jpg)

**Comment by Edzelf** [comment]
See the document.  Search for "TFT library patches".

**Comment by samand587** [comment]
Made changes to TFT_ILI9163C.cpp , nothing has changed- the screen is upside down, on the left there is a white stripe for a quarter of the screen. What else can I see?
![IMG_20211104_181031](https://user-images.githubusercontent.com/82581244/140327555-f924b06c-86c1-4bfd-92e1-330f09d103fc.jpg)

**Comment by samand587** [comment]
I won the white stripe. How can I rotate the screen?

**Comment by samand587** [comment]
Line 1825: 
tft.setRotation ( 1 ) Excellent solution! The question is closed. Thanks!
