### ISSUE TITLE
Make AsyncMqttClient.h optional like USETFT

### ISSUE THREAD

**Issue by NoNeedForAName123** [Edzelf/Esp-radio#25]
please add download reference to AsyncMqttClient.h to documentation and make the usage of Mqtt configurable.
see https://github.com/NoNeedForAName123/Esp-radio/blob/master/Esp_radio.ino how it worked for me.

**Comment by NoNeedForAName123** [comment]
pls. see https://github.com/NoNeedForAName123/Esp-radio/blob/master/Esp_radio.ino how it worked for me.

**Comment by Edzelf** [comment]
If you mean "upload", thats already documented.  You can switch off Mqtt by removing the "mqtt"-lines in the radio.ini file.  I documented the last feature in the new pdf-file.

**Comment by NoNeedForAName123** [comment]
Sorry, I mean in the ESP-radio.pdf in the chapter "Arduino IDE installation for Esp-radio" there is the download location for the AsyncMqttClient missing. So even with switching off mqtt in the ini file compilation fails:

`/Esp-radio/Esp-radio.ino:113:29: fatal error: AsyncMqttClient.h: No such file or directory
 #include <AsyncMqttClient.h>

https://github.com/marvinroger/async-mqtt-client
                             ^
compilation terminated.`

**Comment by Edzelf** [comment]
Fixed.
