### ISSUE TITLE
How to erase EEPROM Radio station

### ISSUE THREAD

**Issue by iqbeul** [Edzelf/Esp-radio#26]
Dear Edzelf
Im trying to create new url radio station through sketch, but eeprom is already filled, how to erase the eeprom and begin to upload only 5-10 station that i need  

Thank you in advance

**Comment by Edzelf** [comment]
The new version doesn't use the EEPROM.   It uses a "radio.ini" file instead.  You can edit your station in this file.  Just look at the example "radio.ini".
