### ISSUE TITLE
Support for m3u URLs

### ISSUE THREAD

**Issue by larbigj** [Edzelf/Esp-radio#30]
Please add support for m3u URLs

**Comment by karawin** [comment]
and xspf and pls to be complete ;-)
Nice project.

**Comment by Edzelf** [comment]
Hmm, I will look into that.

**Comment by larbigj** [comment]
mp3: http://www.rockantenne.de/webradio/rockantenne.m3u

aac: http://www.rockantenne.de/webradio/rockantenne.aac.pls

**Comment by Edzelf** [comment]
m3u playlists are now supported.
