### ISSUE TITLE
does not work with hidden SSID

### ISSUE THREAD

**Issue by zajaklis** [Edzelf/Esp-radio#4]
i have tried pw file for hidden ssid, unable to connect...

**Comment by Edzelf** [comment]
I understand.  You have to unhide the SSID or change the software a bit.

**Comment by Edzelf** [comment]
See my fix on stations like "skonto.ls.lv:8002/mp3"

**Comment by Edzelf** [comment]
Hidden SSID is now possible.  Just make sure that there is a password file for the hidden SSID.  This must be the only password file in de SPIFFS file system.

**Comment by zajaklis** [comment]
great, just tested...
now i can connect to hidden ssid
Thank you
