### ISSUE TITLE
url with /xxxx

### ISSUE THREAD

**Issue by zajaklis** [Edzelf/Esp-radio#5]
Can you include support for url's like http://skonto.ls.lv:8002/mp3  ??
I can listen radio by adding "skonto.ls.lv:8002" to favourites and "/mp3" part in code: mp3client.print ( String ( "GET /mp3 HTTP/1.1\r\n" ) but this will breaks functionality for other radio streams.
Sooory, bad english

**Comment by Edzelf** [comment]
I will try to add that to the code.
