### ISSUE TITLE
Connect To Website

### ISSUE THREAD

**Issue by Sander0542** [Edzelf/Esp-radio#54]
Hello,

Ed, I have a question, I'm trying to make a ESP8266 with a Temprature Sensor (DS18B20), How can I send data to a url with parameter like this: `example.com/add.php?room=livingroom&temp=20.5`
Could you please help me?

Regards,
Sander Jochems

**Comment by Edzelf** [comment]
I will send you an example.

**Comment by Sander0542** [comment]
Thank you very much!

**Comment by Sander0542** [comment]
When do you will send it?

**Comment by Edzelf** [comment]
Already send it through the contactform on you site.

**Comment by Sander0542** [comment]
That one didnt work, the last week, there was a bug, could you please send it to contact@sanderjochems.nl?
