### ISSUE TITLE
Any plan porting to ESP32?

### ISSUE THREAD

**Issue by GabeHC** [Edzelf/Esp-radio#64]
is there any plan to port it to ESP32?

**Comment by Edzelf** [comment]
I do not own an ESP32 at the moment.  But it shouldn't be to hard to port it.

**Comment by Edzelf** [comment]
ESP32 version is released.

**Comment by bbx10** [comment]
Thanks @Edzelf. ESP32 version working on one of these https://github.com/espressif/arduino-esp32#esp32dev-board-pinmap and Adafruit VS1053 breakout board.

**Comment by GabeHC** [comment]
Thanks! and it works much better than ESP8266
