### ISSUE TITLE
Diodes have to be schottky

### ISSUE THREAD

**Issue by andybrk** [Edzelf/Esp-radio#80]
Just I found why I had so much problems that the SW can't write any registers. (volume change doesn't work and so on)
I mad tests and found that if I uncomment the calls of "printDetails" then all registers of the vs1053 shows allways 0.
I try to put the reset pin on an extra port of the ESP8266 and modify the reset of the VS1053 for that. This works fine. 
So I began to investigate and found that the high level on the reset port of the VS1053 with the diodes seems a little bit to low. I did use universal diodes 1N4848 for that. I did change the resistor from 1k to 10k, but this was not successful
As I replace this diodes with schottky type (1N 5817, just I had in my stuffs) then it works fine.
May be I have a bad exemplar of the VS1053, but for security should use schottky diodes for the reset circuit. Also I did change the resistor from 1k to 10k.

**Comment by Edzelf** [comment]
Using Shottky diodes is a good idea.  You may omit the reset circuit.  Just add a pull-up on XRST.  Or connect it to the reset line of the ESP8266.
