### ISSUE TITLE
Feature Request: Add a2dp as soon as it is available in arduino-esp32

### ISSUE THREAD

**Issue by 68erDirk** [Edzelf/Esp-radio#93]
One of the great improvements of ESP32 is the integrated bluetooth feature. For ESP-idf there is already an example for a a2dp sink (https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/a2dp_sink). I hope this will soon be available in the arduino esp32 as well. At that point I would appreciate to have it integrated in order to be able to connect a smartphone vie bluetooth and play the a2dp stream on my esp-radio.

**Comment by Edzelf** [comment]
Please put ESP32-Radio issues at the ESP32-Radio repository.

**Comment by 68erDirk** [comment]
Sorry. Changed now!

**Comment by Edzelf** [comment]
Have to wait for Arduino version indeed.
